user_dir: "/home/azureuser"
app_port: 8000
app_user: azureuser
service:
  workingdir: "{{user_dir}}/devopsAdmin/student_management"
  execstart: "{{user_dir}}/devopsAdmin/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind  student_management.wsgi:application"

djangoservice:
  workingdir: "{{user_dir}}/devopAdmin/student_management"
  execstart: "{{user_dir}}/devopsAdmin/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind  student_management.wsgi:application"



app:
  env:
    SQLALCHEMY_DATABASE_URI: postgres://myprojectuser:password@db:5432/myproject
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SECRET_KEY: test123

django:
  env:
    SECRET_KEY: test123
    DATABASE_URL: postgres://myprojectuser:password@db:5432/myproject


django2:
  env:
    SECRET_KEY: test123
    DATABASE_URL: postgres://myprojectuser:password@20.223.161.90:5432/myproject

